package ejercicio1.main;

public class MainExcepciones {
	
	public static void main(String[] args) {
		
		String cadena = null;
		
		//try {
			cadena = "VALE";
			cadena.length();
			cadena.charAt(4);
		/*} catch (NullPointerException e) {
			System.out.println("entra por null");
			e.printStackTrace();
		}catch (Throwable e) {
			// TODO: handle exception
			System.out.println("entra por throw");
			e.printStackTrace();
		}*/
	}

}
